export const GAME_JOIN_ATTEMPT_BEGIN = 'GAME_JOIN_ATTEMPT_BEGIN';
export const GAME_JOIN_ATTEMPT_STARTED = 'GAME_JOIN_ATTEMPT_STARTED';
export const GAME_JOIN_ATTEMPT_COMPLETE = 'GAME_JOIN_ATTEMPT_COMPLETE';
export const GAME_JOIN_ATTEMPT_FAILURE = 'GAME_JOIN_ATTEMPT_FAILURE';

export const GAME_JOIN_PICK_PLAYER_BEGIN = 'GAME_JOIN_PICK_PLAYER_BEGIN';
export const GAME_JOIN_PICK_PLAYER_STARTED = 'GAME_JOIN_PICK_PLAYER_STARTED';
export const GAME_JOIN_PICK_PLAYER_COMPLETE = 'GAME_JOIN_PICK_PLAYER_COMPLETE';
export const GAME_JOIN_PICK_PLAYER_FAILURE = 'GAME_JOIN_PICK_PLAYER_FAILURE';

export const GAME_CREATE_BEGIN = 'GAME_CREATE_BEGIN';
export const GAME_CREATE_STARTED = 'GAME_CREATE_STARTED';
export const GAME_CREATE_COMPLETE = 'GAME_CREATE_COMPLETE';
export const GAME_CREATE_FAILURE = 'GAME_CREATE_FAILURE';

export const GAME_PING_START = 'GAME_PING_START';
export const GAME_PING_SUCCESS = 'GAME_PING_SUCCESS';
export const GAME_PING_FAILURE = 'GAME_PING_FAILURE';

export const GAME_MOVE_BEGIN = 'GAME_MOVE_BEGIN';
export const GAME_MOVE_STARTED = 'GAME_MOVE_STARTED';
export const GAME_MOVE_COMPLETE = 'GAME_MOVE_COMPLETE';
export const GAME_MOVE_FAILURE = 'GAME_MOVE_FAILURE';

export const GAME_EXIT = 'GAME_EXIT';

export const DISMISS_ERROR = 'DISMISS_ERROR';
